name: investigut

channels:
  - defaults
  - bioconda

dependencies:  # Newer package versions may also work, but need to be verified
  - python=3.11
  - numpy=1.24.3
  - scipy=1.10.1
  - matplotlib=3.7.1
  - seaborn=0.13.0
  - pandas=1.5.3
  - statsmodels=0.13.5
  - ete3=3.1.2
  - bioconda::diamond=2.1.8